server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 47.108.167.244:8848 # nacos服务地址
    gateway:
      routes: # 网关路由配置
        - id: user-service # 路由id，自定义，只要唯一即可
          uri: lb://userservice # 路由的目标地址 lb就是负载均衡，后面跟服务名称 loadBalance
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/wechat/**, /user/** # 这个是按照路径匹配，只要以/user/开头就符合要求

        - id: good-service
          uri: lb://goodservice
          predicates:
            - Path=/goods/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # 允许哪些网站的跨域请求 allowedOrigins: “*” 允许所有网站
            # - "http://47.108.167.244:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
