version: "3.2"

services:
  nacos:
    image: nacos/nacos-server:v2.1.0
    environment:
      MODE: standalone
    ports:
      - "8848:8848"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "$PWD/mysql/data:/var/lib/mysql"
      - "$PWD/mysql/conf:/etc/mysql/conf.d/"
    ports:
      - "3306:3306"
  userservice:
    build: ./user
  orderservice:
    build: ./order
  goodservice:
    build: ./good
  gateway:
    build: ./gateway
    ports:
      - "10010:10010"
