server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.108.167.244:3306/shopping-user?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: God0812?.
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice
  cloud:
    nacos:
      server-addr: 47.108.167.244:8848 # nacos服务地址
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.ycj.user.pojo
  configuration:
    map-underscore-to-camel-case: true