server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://47.108.167.244:3306/shopping-order?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: God0812?.
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.ycj.order.pojo
  configuration:
    map-underscore-to-camel-case: true